const CUSTOMER_SITES = {
    qiqi: {
        "api_1": {"api": "https://api.1080zyku.com/inc/api_mac10.php", "name": "TV-1080资源"},
    "api_2": {"api": "https://155api.com/api.php/provide/vod", "name": "AV-155资源"},
    "api_3": {"api": "https://360zy.com/api.php/provide/vod", "name": "TV-360资源"},
    "api_4": {"api": "https://ckzy.me/api.php/provide/vod", "name": "TV-CK资源"},
    "api_5": {"api": "https://api.ukuapi.com/api.php/provide/vod", "name": "TV-U酷资源"},
    "api_6": {"api": "https://api.ukuapi88.com/api.php/provide/vod", "name": "TV-U酷资源"},
    "api_7": {"api": "https://ikunzyapi.com/api.php/provide/vod", "name": "TV-ikun资源"},
    "api_8": {"api": "https://api.wujinapi.cc/api.php/provide/vod", "name": "TV-wujinapi无尽"},
    "api_9": {"api": "https://cj.yayazy.net/api.php/provide/vod", "name": "TV-丫丫点播"},
    "api_10": {"api": "https://api.guangsuapi.com/api.php/provide/vod", "name": "TV-光速资源"},
    "api_11": {"api": "https://collect.wolongzyw.com/api.php/provide/vod", "name": "TV-卧龙点播"},
    "api_12": {"api": "https://collect.wolongzy.cc/api.php/provide/vod", "name": "TV-卧龙资源"},
    "api_13": {"api": "https://wolongzyw.com/api.php/provide/vod", "name": "TV-卧龙资源"},
    "api_14": {"api": "https://tyyszy.com/api.php/provide/vod", "name": "TV-天涯资源"},
    "api_15": {"api": "https://cj.rycjapi.com/api.php/provide/vod", "name": "TV-如意资源"},
    "api_16": {"api": "https://zy.xmm.hk/api.php/provide/vod", "name": "TV-小猫咪资源"},
    "api_17": {"api": "https://api.xinlangapi.com/xinlangapi.php/provide/vod", "name": "TV-新浪点播"},
    "api_18": {"api": "https://api.wujinapi.com/api.php/provide/vod", "name": "TV-无尽资源"},
    "api_19": {"api": "https://api.wujinapi.me/api.php/provide/vod", "name": "TV-无尽资源"},
    "api_20": {"api": "https://api.wujinapi.net/api.php/provide/vod", "name": "TV-无尽资源"},
    "api_21": {"api": "https://wwzy.tv/api.php/provide/vod", "name": "TV-旺旺短剧"},
    "api_22": {"api": "https://api.wwzy.tv/api.php/provide/vod", "name": "TV-旺旺资源"},
    "api_23": {"api": "https://bfzyapi.com/api.php/provide/vod", "name": "TV-暴风资源"},
    "api_24": {"api": "http://zuidazy.me/api.php/provide/vod", "name": "TV-最大点播"},
    "api_25": {"api": "https://api.zuidapi.com/api.php/provide/vod", "name": "TV-最大资源"},
    "api_26": {"api": "https://m3u8.apiyhzy.com/api.php/provide/vod", "name": "TV-樱花资源"},
    "api_27": {"api": "https://api.yparse.com/api/json", "name": "TV-步步高资源"},
    "api_28": {"api": "https://api.niuniuzy.me/api.php/provide/vod", "name": "TV-牛牛点播"},
    "api_29": {"api": "http://caiji.dyttzyapi.com/api.php/provide/vod", "name": "TV-电影天堂"},
    "api_30": {"api": "https://api.bwzyz.com/api.php/provide/vod", "name": "AV-百万资源"},
    "api_31": {"api": "https://api.apibdzy.com/api.php/provide/vod", "name": "TV-百度云资源"},
    "api_32": {"api": "https://api.1080zyku.com/inc/apijson.php/", "name": "TV-神马云"},
    "api_33": {"api": "https://suoniapi.com/api.php/provide/vod", "name": "TV-索尼资源"},
    "api_34": {"api": "https://www.hongniuzy2.com/api.php/provide/vod", "name": "TV-红牛资源"},
    "api_35": {"api": "https://caiji.maotaizy.cc/api.php/provide/vod", "name": "TV-茅台资源"},
    "api_36": {"api": "https://www.huyaapi.com/api.php/provide/vod", "name": "TV-虎牙资源"},
    "api_37": {"api": "https://caiji.dbzy.tv/api.php/provide/vod", "name": "TV-豆瓣资源"},
    "api_38": {"api": "https://dbzy.tv/api.php/provide/vod", "name": "TV-豆瓣资源"},
    "api_39": {"api": "https://hhzyapi.com/api.php/provide/vod", "name": "TV-豪华资源"},
    "api_40": {"api": "https://subocaiji.com/api.php/provide/vod", "name": "TV-速博资源"},
    "api_41": {"api": "https://cj.lziapi.com/api.php/provide/vod", "name": "TV-量子资源"},
    "api_42": {"api": "https://jinyingzy.com/api.php/provide/vod", "name": "TV-金鹰点播"},
    "api_43": {"api": "https://jyzyapi.com/api.php/provide/vod", "name": "TV-金鹰资源"},
    "api_44": {"api": "https://sdzyapi.com/api.php/provide/vod", "name": "TV-閃電资源"},
    "api_45": {"api": "https://cj.ffzyapi.com/api.php/provide/vod", "name": "TV-非凡资源"},
    "api_46": {"api": "https://p2100.net/api.php/provide/vod", "name": "TV-飘零资源"},
    "api_47": {"api": "https://mozhuazy.com/api.php/provide/vod", "name": "TV-魔爪资源"},
    "api_48": {"api": "https://caiji.moduapi.cc/api.php/provide/vod", "name": "TV-魔都动漫"},
    "api_49": {"api": "https://www.mdzyapi.com/api.php/provide/vod", "name": "TV-魔都资源"},
    "api_50": {"api": "https://json.heimuer.xyz/api.php/provide/vod", "name": "TV-黑木耳"},
    "api_51": {"api": "https://json02.heimuer.xyz/api.php/provide/vod", "name": "TV-黑木耳点播"},
    "api_52": {"api": "https://91md.me/api.php/provide/vod", "name": "AV-91麻豆"},
    "api_53": {"api": "http://lbapiby.com/api.php/provide/vod", "name": "AV-AIvin"},
    "api_54": {"api": "https://jkunzyapi.com/api.php/provide/vod", "name": "AV-JKUN资源"},
    "api_55": {"api": "https://api.souavzy.vip/api.php/provide/vod", "name": "AV-souav资源"},
    "api_56": {"api": "https://lbapi9.com/api.php/provide/vod", "name": "AV-乐播"},
    "api_57": {"api": "https://aosikazy.com/api.php/provide/vod", "name": "AV-奥斯卡"},
    "api_58": {"api": "https://Naixxzy.com/api.php/provide/vod", "name": "AV-奶香香"},
    "api_59": {"api": "https://slapibf.com/api.php/provide/vod", "name": "AV-森林资源"},
    "api_60": {"api": "https://www.xrbsp.com/api/json.php", "name": "AV-淫水机资源"},
    "api_61": {"api": "https://apiyutu.com/api.php/provide/vod", "name": "AV-玉兔"},
    "api_62": {"api": "http://fhapi9.com/api.php/provide/vod", "name": "AV-番号资源"},
    "api_63": {"api": "https://www.kxgav.com/api/json.php", "name": "AV-白嫖"},
    "api_64": {"api": "https://www.jingpinx.com/api.php/provide/vod", "name": "AV-精品"},
    "api_65": {"api": "https://www.msnii.com/api/json.php", "name": "AV-美少女"},
    "api_66": {"api": "https://apilsbzy1.com/api.php/provide/vod", "name": "AV-老色逼"},
    "api_67": {"api": "https://api.sexnguon.com/api.php/provide/vod", "name": "AV-成人资源"},
    "api_68": {"api": "https://api.zhuoyl.com/api.php/provide/vod", "name": "AV-卓越资源"},
    "api_69": {"api": "https://api.13av.cc/api.php/provide/vod", "name": "AV-13av"},
    "api_70": {"api": "https://www.xbapi.net/api.php/provide/vod", "name": "AV-xbapi"},
    "api_71": {"api": "https://www.88api.com/api.php/provide/vod", "name": "AV-88api"},
    "api_72": {"api": "https://api.soboys.com/api.php/provide/vod", "name": "AV-索博"}
   
    }
};

// 调用全局方法合并
if (window.extendAPISites) {
    window.extendAPISites(CUSTOMER_SITES);
} else {
    console.error("错误：请先加载 config.js！");
}
